### PR TITLE
Thomvet patch

### PR DESCRIPTION
**Pull request by thomvet**
This PR is a semi-big update of the code-base:
- updated the open62541_jll package (v1.3.7 and v1.3.8 available now). 
- Updated automatic code generation; including a workaround to get the julia_types and type_names vectors automated (epilogue of generator.jl is handled manually now).
- UA_NodeId struct is now rewritten automatically (which was needed to have the code running).
- code follows sciml automatic formatter after generation.
- added semver compat bounds to all packages used.
- introduced a few higher order functions to add variable nodes to servers.
- testsuite contains Aqua.jl tests (piracy, compat bounds, exports, etc.).
- introduced a small test suite and moved to Github actions for CI. There are some commented out tests in the files that pass locally, but I struggle to get them to run on the Github servers (it's a threading issue...sorry, I am a newbie on those issues).
- a few bugfixes were introduced as well (some array indexing wasn't fully correct; dimensions etc.).
- finally, due to these changes, I bumped the version.

I hope that this is a step in the right direction for the package :)

### CODE REVIEW

**Comment by martinkosch** [comment]
Hi @thomvet, 
wow, that indeed looks like a step in the right direction! I am glad you were able to figure out the package :)
I hope I find some time tomorrow to make a few tests before merging.

**Comment by martinkosch** [comment]
I added and changed a few things: 
- The default attributes are now loaded and exported at `__init__()`
- Write functionality and tests for scalars and arrays has been added
- I replaced some minor parts in your code with existing function calls, especially the eval call (let me know if I messed somthing up) 
- The new exception call arguments had a small bug which I corrected
- I replaced some of the `Ptr` arguments in the generated functions in `types.jl` with `Ref`. I hope this makes function calls easier without leading to memory access issues

For some strange reason, `UA_generate_variable_attributes()` fails to set the scalar values in `add_change_var_scalar.jl`. However, it works again when I add an additional line `@show unsafe_load(attr.value)` in `server.jl`. Do you have any clue what could be the reason for this strange behavior? 

Let me know if you have any ideas or issues. :)

**Comment by thomvet** [comment]
I'll have a better look tonight. Regarding the strange bug: probably an issue with memory handling somehow. These things are still super strange to me.

**Comment by martinkosch** [comment]
It seems to work when `UA_Variant_setScalarCopy()` is used. Apparently, C has trouble accessing the variables managed by Julia. 

Previously, I tried to handle some variables using Julia's memory space, hoping that this would enable improved wrapping and would make the memory management easier. However, I feel the leftovers from this approach should be removed in the future and almost everything should be moved to the C memory space.

**Comment by thomvet** [comment]
Please, wait with running more CI on this repo. I am narrowing down the problem on my forked repository... it seems that certain combinations of types and array sizes do not work together? 

Confirmed so far:

- 1D and 2D arrays work with Int16, Int32, Int64, Float32, Float64, Bool types.
- 3D arrays do not work with Int16 (CI process hangs indefinitely)
- 3D arrays work with Float64 and Bool types.
- 3D array does not work with Float32.
- Other combinations not tested yet.

**Comment by thomvet** [comment]
Yes! The worker process change was really good!

**Comment by martinkosch** [comment]
Yep, it luckily feels much more robust than using threads. Also, the setting of the server and client running in different processes should be more realistic. For some strange reason, however, I had to use the native `@testset` instead of `@safetestset`. Otherwise, the client is not able to connect to the server. 

I think the original idea of this PR of getting the package back to life should be completed now, right? Maybe its time to merge and handle future issues separately. It feel like the package could acutally be registered soon with only a few changes, especially tests and documentation.

**Comment by thomvet** [comment]
I agree that we are close here and should merge this soon, then think about separate issues standing in the way of a release and registration.

However, did you check whether the tests pass locally for you?

In the scalar test code, the comparisons on line 82 fail for me, i.e., what client reads is not the same that was put on the server (memory issue??) and if I comment the scalar tests and just run the arrays, then I get "BadNodeIdUnknown" errors. 

Can you try? 

My `versioninfo()`:
```
Julia Version 1.10.0-rc1
Commit 5aaa948543 (2023-11-03 07:44 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 24 × 12th Gen Intel(R) Core(TM) i7-12850HX
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, alderlake)
  Threads: 2 on 24 virtual cores
```

This is why I included Julia 1.10 and Windows in the CI.yml testset as well. But both seem to pass on the Github servers? So, Windows and Julia 1.10 are likely not the causes for my local test failures. Hm.

**Comment by martinkosch** [comment]
All tests are passing on my machine for yout latest commit b13f86a. I am still running an older version of Julia. 
My versioninfo():

```
Julia Version 1.8.2
Commit 36034abf26 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8
```

**Comment by thomvet** [comment]
The tuple commit somehow made tests pass for me locally as well. I think it's better practice not to mix number types too liberally in an array (implicit type conversion), so opted for tuples instead.

I made some more edits on dispatching more conveniently in the client.jl and server.jl file. Also made a few more tests on the server_write.jl file where I am just reading and then writing things back on a variable node. 

When testing older Julia versions (namely Julia 1.6, the current release with long term support), I got an error about a permutation not being allowed in the data_handling.jl file (last test).

I'll have another look at that tomorrow with fresh eyes. Anyhow, for now the package passes tests on Julia 1.9 and the upcoming Julia 1.10, which is fair enough! :)

**Comment by thomvet** [comment]
Ok, i got rid of that error (apparently Julia 1.6 doesn't like UInts when specifying the permutation to adjust between Julia and C style indexing). 

Also updated the library to 1.3.9, introduced some more tests (server_write.jl) and cleaned up a dependency. I also made the last Aqua test passing by changing the init function (see aqua.jl manual for why).

Tests on Julia 1.6 are still not always passing (they hang between simple client test and scalar tests), which may be a problem coming from how processes get shut down (is there a more graceful way?). They sometimes do pass, but it's flaky. 

1.6 is also the minimum that could possibly be supported, because the binary (open62541_jll) requires it. 

Anyhow, tests pass reliably on Julia 1.9 and the upcoming 1.10. 

From my perspective the PR is ready to merge now. What do you think?

**Comment by martinkosch** [comment]
It looks good to merge from my perspective! 

When I started the package in 2021, I remember encountering much more surprising errors than with the current version. Back then, I used Julia 1.6. It seems like some important things changed on this side. 

I also tried to shut down the server process more gracefully, but I still cannot think of a better way without manipulating the jll itself or using the unstable threaded approach. I think it is ok to leave it like that for now, especially if it does not affect the actual package usage.

**Pull request merged**
