### PR TITLE
Update to open62541 1.4.6

### PR DESCRIPTION
**Pull request by thomvet**
This PR will be an update to the current release branch of open62541, i.e., the 1.4 branch. The 1.4.0 release is buggy (json encoding of types was broken, 1.4.1 was a hotfix release to correct this), so I am skipping it. Going from 1.3.x to 1.4.1 is a breaking change. There is about twice the number of UA_... types in 1.4.1 compared to 1.4.0 and previous versions, 388 vs 227; hence the ordering of types is different and the wrapper looks different as well.

The generator has been revised and the current tests are passing, but there are a few things that I want to add in a 0.2.0 version (which it needs to be, because of the breaking changes introduced in open62541 v1.4.1 vs. 1.3.x). 
 
Namely, open62541 v1.4,1 introduces rational numbers; I want to provide some infrastructure for these in this PR as well (same as done for the complex number types). These will not be implemented as full Julia number types (that would require overloading all operators like +,-, etc.), but Julia Rational numbers will be converted to the respective UA types when writing to a server (and vice-versa) when reading. This was already how complex numbers were handled by the library, but I'll need to add some documentation about this as well.

The following items need to be done.
- [x] Add functions to helper_functions.jl
- [x] Add Rational(x::Union{UA_RationalNumber, UA_UnsignedRationalNumber} to types.jl
- [x] Add attribute generation for UA_RationalNumber and UA_UnsignedRationalNumber (attribute_generation.jl)
- [x] Add rational types to dispatch in highlevel_types.jl
- [x] add tests in add_change_var_scalar.jl
- [x] add tests in add_change_var_array.jl
- [x] add tests in highlevel_types (JUA_Variant)

Documentation:

- [x] Add UA_xxx_equal docstrings
- [x] Documentation: explain better how rational and complex numbers are handled by the library.

### CODE REVIEW

**Comment by thomvet** [comment]
Ok, some progress here. Not much left to be done to have this working; I'll probably manage to finalize this tonight :)

**Comment by thomvet** [comment]
@martinkosch: This would be ready for a review. The only thing I would like to add are a few examples to address questions in https://github.com/martinkosch/Open62541.jl/issues/28. That should be a +/- straightforward translation of some of the tests that already exist. Hope to get it done soon!

**Review by martinkosch — APPROVED** [review]
Sorry, I completely overlooked your request! 
It looks all good to me. Nice to see that the version update is working :)

**Comment by thomvet** [comment]
Thanks for the approval and no worries. There was also the holiday period in between :). I am hoping that I can wrap up the documentation improvements mentioned above very soon (end of week at the latest). 

I'll then proceed to merge if things are still working as expected.

**Comment by thomvet** [comment]
All good now! Also updated the jll wrapper to open62541 1.4.6 (newest version available).

**Pull request merged**
