### PR TITLE
add historizing features to _jll; re-run generator

### PR DESCRIPTION
**Pull request by thomvet**
Generated a new version of open62541_jll that contains the features necessary for historizing nodes (nodes that safe the evolution of their value over time). Tests still pass locally.

### CODE REVIEW

**Comment by martinkosch** [comment]
Good work! I vaguely remember that I purposely deactivated the historizing features previously but I cannot remember why exactly. Possibly, there was a bug back then that has been fixed in the meantime. It should be fine if you managed to get this far :) 

Are you planning to add more commits to this PR or is this ready to merge? There is definitively some clean-up needed from my side to remove all the old unsafe functions in `type.jl` but this should be of no concern here.  I hope I get to this soon.

**Comment by thomvet** [comment]
I need to have another look at this; have some local uncommitted changes that I have to see whether it makes sense to include here. I'll get back to you by Tuesday latest :-)

**Comment by thomvet** [comment]
Cleaned up a little and made the generator a little more foolproof (now sets compat entry automatically to the version that it has been run on - otherwise things like version number constants are out of sync...)

**Comment by thomvet** [comment]
Could we merge this? I have another large PR coming, but it would probably be good to get this one merged first (and then I'll sort out any conflicts that emerge).

**Review by martinkosch — APPROVED** [review]

**Pull request merged**
